locals {
  # Rootless quadlet units on prod3, installed verbatim to
  # ~/.config/containers/systemd/ for user prodmin.
  # Map: source filename => systemd user unit generated by quadlet.
  prod3_quadlet_files = {
    "13ft.container"                = "13ft.service"
    "activepieces.container"        = "activepieces.service"
    "certwarden.container"          = "certwarden.service"
    "docker-socket-proxy.container" = "docker-socket-proxy.service"
    "internal.network"              = "internal-network.service"
    "netdata.container"             = "netdata.service"
    "netdatacache.volume"           = "netdatacache-volume.service"
    "netdatalib.volume"             = "netdatalib-volume.service"
    "openviking.container"   = "openviking.service"
       "semaphore.container"    = "semaphore.service"
    "services.pod"                  = "services-pod.service"
    "stash.container"               = "stash.service"
    "traefik.container"             = "traefik.service"
  }
}

resource "null_resource" "prod3_quadlets" {
  for_each = local.prod3_quadlet_files

  triggers = {
    content = filesha256("${path.module}/quadlet/${each.key}")
  }

  connection {
    type  = "ssh"
    host  = var.prod3_host
    user  = "prodmin"
    agent = true
  }

  provisioner "remote-exec" {
    inline = [
      "mkdir -p ~/.config/containers/systemd",
    ]
  }

  provisioner "file" {
    source      = "${path.module}/quadlet/${each.key}"
    destination = ".config/containers/systemd/${each.key}"
  }

  provisioner "remote-exec" {
    inline = [
      "export XDG_RUNTIME_DIR=/run/user/$(id -u)",
      "systemctl --user daemon-reload",
      "systemctl --user restart ${each.value}",
    ]
  }
}

resource "null_resource" "openviking_config" {
  triggers = {
    content = filesha256("${path.module}/quadlet/ov.conf")
  }

  connection {
    type  = "ssh"
    host  = var.prod3_host
    user  = "prodmin"
    agent = true
  }

  provisioner "remote-exec" {
    inline = [
      "sudo mkdir -p /var/opt/openviking/data",
      "sudo chown -R $USER:$USER /var/opt/openviking/data"
    ]
  }

  provisioner "file" {
    source      = "${path.module}/quadlet/ov.conf"
    destination = "/tmp/ov.conf"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo mv /tmp/ov.conf /var/opt/openviking/data/ov.conf"
    ]
  }
}
